### ISSUE TITLE
mdl_void_hosts.txt weird/emptyish/unmaintained?

### ISSUE THREAD

**Issue by rwv37** [cyclaero/void-zones-tools#10]
I just happened to notice that ``mdl_void_hosts.txt`` on my server only has one non-comment line in it, that being ``127.0.0.1 localhost``. That seemed weird, so I started looking into it a little. The file is pulled from [http://www.malwaredomainlist.com/hostslist/hosts.txt](http://www.malwaredomainlist.com/hostslist/hosts.txt), which in fact does have only that one line.

I found various things on the web ([example here](https://github.com/safing/intel-data/issues/26)) saying that malwaredomainlist.com no longer maintains the file. So I guess maybe ``void-zones-update.sh`` shouldn't use it anymore? And maybe even it should actually delete the file if present?

It looks to me like [the most recent commit in this project](https://github.com/cyclaero/void-zones-tools/commit/62e9159292d384e7c77160e1afb8e8182915c9dc) is about a very similar thing, but for a different file (``jdom_void_list.txt``, pulled from "malwaredomains.com" rather than "malwaredomainlist.com").

My apologies in advance if I'm misunderstanding something.

**Comment by cyclaero** [comment]
Thank you for reporting the issue. I just removed MDL from the update shell script.
