### ISSUE TITLE
Request for extension

### ISSUE THREAD

**Issue by gearhead** [cyclaero/void-zones-tools#5]
your scripts process a list of sites into a format for unbound and the readme shows how to add a list, site by site. Is ther a script that can process a list of pages with lists from another site? An example is: https://v.firebog.net/hosts/lists.php?type=tick. I am trying to use the fetch-o -/... process and have not been able to get it to work.

**Comment by cyclaero** [comment]
The following shell script should do the job:

    #!/bin/sh

    metalist=`fetch -qo- "https://v.firebog.net/hosts/lists.php?type=tick"`

    rm -rf /usr/local/etc/void-zones/y_void_list.txt
    for url in $metalist ; do
       fetch -qo- "$url" >> /usr/local/etc/void-zones/y_void_list.txt
    done
