### ISSUE TITLE
Bus error on armv6

### ISSUE THREAD

**Issue by aft90** [cyclaero/void-zones-tools#6]
This happened on a Raspberry Pi 1 model B (armv6 processor) running FreeBSD 12.2-RELEASE. When running `hosts2zones` (either as installed from `pkg` or compiled from source) on any input, the program terminates with a bus error and dumps core. Interestingly, the error only seems to occur when the program is compiled with optimizations - turning optimizations off with `-O0` makes it run fine. 

After compiling it in debug mode I tracked down the source of the error to [here](https://github.com/cyclaero/void-zones-tools/blob/baf82af947329fa62b02b9ea9e9d6eefea90ff9e/hosts2zones.c#L109), specifically when the `char` pointer `line` is dereferenced as an 8-byte integer. I suspect this is because, according to the [ARM docs](https://developer.arm.com/documentation/dui0472/m/compiler-command-line-options/--unaligned-access----no-unaligned-access)
>  ARM processors do not provide support for unaligned doubleword accesses, for example unaligned accesses to long long integers. Doubleword accesses must be either eight-byte or four-byte aligned. 

Since obviously there is no way to guarantee that `line` will be aligned, it's just a pointer in a text stream.

**Comment by aft90** [comment]
I've got a potential fix suggested in #7 . I realise you probably avoided `strncmp` for performance reasons, but I did do some manual performance testing with the predefined blocklists in the script and didn't see any degradation.

**Comment by cyclaero** [comment]
Thank you for reporting the issue. I dislike strncmp() because it is THE overkill for the given purpose. Please try, whether the following Diff works for your RPi — It does work on my BBB (armv7). In case yes, I will commit that change.

Best regards

Rolf

[arm-unaligned-64bit-fix.diff.txt](https://github.com/cyclaero/void-zones-tools/files/5762022/arm-unaligned-64bit-fix.diff.txt)

**Comment by aft90** [comment]
Hi! Thank for taking a look at this. Yeah, the change does work, but I had to change `boolean` to `bool` in `binutils.h`.

**Comment by aft90** [comment]
Actually, are are a few things I'm not clear on.
1. In your new code, after using `cmp10` to compare to `127.0.0.1` you no longer advance the pointer by 2 like you did previously. However the code still seems to work, producing the correct result. I'm not sure exactly why it still works, I suspect some kind of weird off-by-one error . What I did notice is that for an input with 3 lines, say
```
127.0.0.1 d1.com
127.0.0.1 d2.com
127.0.0.1 d3.com
```
the program with your changes outputs:
```
Number of Hosts: 4
Number of Zones: 3
```

Whereas your original code outputs:
```
Number of Hosts: 3
Number of Zones: 3
```
Maybe there's something I'm missing in your fix but it seems to me like it's better to put the `line+=2` statement back. 

2. Shouldn't `compare9` be used to compare to `localhost` instead of `compare10`?

**Comment by cyclaero** [comment]
> Hi! Thank for taking a look at this. Yeah, the change does work, but I had to change `boolean` to `bool` in `binutils.h`.

Yes, sorry, I sent the wrong Diff. The actual working one had `bool` already in place.

> Actually, are are a few things I'm not clear on.
> 
> 1. In your new code, after using `cmp10` to compare to `127.0.0.1` you no longer advance the pointer by 2 like you did previously. However the code still seems to work, producing the correct result. I'm not sure exactly why it still works, I suspect some kind of weird off-by-one error . What I did notice is that for an input with 3 lines, say
> 
> ```
> 127.0.0.1 d1.com
> 127.0.0.1 d2.com
> 127.0.0.1 d3.com
> ```
> 
> the program with your changes outputs:
> 
> ```
> Number of Hosts: 4
> Number of Zones: 3
> ```
> 
> Whereas your original code outputs:
> 
> ```
> Number of Hosts: 3
> Number of Zones: 3
> ```
> 
> Maybe there's something I'm missing in your fix but it seems to me like it's better to put the `line+=2` statement back.

Very good observation, I really missed this one, and I corrected the code according to your suggestion.

> 1. Shouldn't `compare9` be used to compare to `localhost` instead of `compare10`?

The compare includes the trailing `nul` char, and therefore it is cmp10().

Here comes a new corrected Diff. If this one is Ok I will commit the changes.

Many thanks again

Rolf

[arm-unaligned-64bit-fix-v2.diff.txt](https://github.com/cyclaero/void-zones-tools/files/5762339/arm-unaligned-64bit-fix-v2.diff.txt)

**Comment by aft90** [comment]
Yeah, the new patch works. Thanks.
